New indentation/line breaks and exit on error building examples

diff --git a/projects/extensibella/examples/build b/projects/extensibella/examples/build
--- a/projects/extensibella/examples/build
+++ b/projects/extensibella/examples/build
@@ -6,6 +6,11 @@ for dir in "${dirs[@]}"
 do
     cd "$dir"
     ./build
+    #check for failure to stop here
+    if [[ $? -ne 0 ]] ; then
+        exit 1
+    fi
+    #display the successful completion
     echo ""
     echo ""
     echo "============================================================"
